name: Ryan Sun
markdown: kramdown
theme: jekyll-theme-minimal
google_analytics: UA-126793910-1
show_downloads: false
title: Ryan Sun
excerpt_separator: <!--more-->
permalink: /blog/:year/:month/:day/:title
future: true
timezone: America/Chicago
